class AllergenLegend {
  static const Map<String, String> legend = {
    "1": "mit Farbstoff",
    "2": "mit Konservierungsstoff",
    "3": "mit Antioxidationsmittel",
    "4": "mit Geschmacksverstärker",
    "5": "mit Phosphat",
    "6": "Oberfläche gewachst",
    "7": "geschwefelt",
    "8": "Oliven geschwärzt",
    "9": "mit Süßungsmitteln",
    "10": "kann bei übermäßigem Verzehr abführend wirken",
    "11": "enthält eine Phenylalaninquelle",
    "12": "kann Restalkohol enthalten",
    "14": "aus Fleischstücken zusammengefügt",
    "15": "mit kakaohaltiger Fettglasur",
    "27": "aus Fischstücken zusammengefügt",
    "Ca": "Cashewnüsse",
    "Di": "Dinkel",
    "Ei": "Eier",
    "Er": "Erdnüsse",
    "Fi": "Fisch",
    "Ge": "Gerste",
    "Gl": "Glutenhaltiges Getreide",
    "Hf": "Hafer",
    "Ha": "Haselnüsse",
    "Ka": "Kamut",
    "Kr": "Krebstiere",
    "Lu": "Lupine",
    "Ma": "Mandeln",
    "ML": "Milch/Laktose",
    "Nu": "Schalenfrüchte/Nüsse",
    "Pa": "Paranüsse",
    "Pe": "Pekannüsse",
    "Pi": "Pistazie",
    "Qu": "Queenslandnüsse/Macadamianüsse",
    "Ro": "Roggen",
    "Sa": "Sesam",
    "Se": "Sellerie",
    "Sf": "Schwefeldioxid/Sulfit",
    "Sn": "Senf",
    "So": "Soja",
    "Wa": "Walnüsse",
    "We": "Weizen",
    "Wt": "Weichtiere",
    "LAB": "mit tierischem Lab",
    "GEL": "mit Gelatine",
  };

  static String? resolve(String code) {
    return legend[code];
  }
}
