-keep class com.builttoroam.devicecalendar.** { *; }

#In app Purchase
-keep class com.amazon.** {*;}
-keep class com.dooboolab.** { *; }
-keep class com.android.vending.billing.**
-dontwarn com.amazon.**
-keepattributes *Annotation*

# Keep WorkManager implementation classes generated by Room to avoid
# reflection NoSuchMethodException during initialization in release builds.
-keep class androidx.work.impl.** { *; }